// app/[locale]/legal/terms-of-service/page.tsx
import { Section } from '@/components/sections/Section';
import { Container } from '@/components/sections/Container';
import { BackgroundPattern } from '@/components/ui/background-pattern';
import Link from 'next/link';
import {
  ArrowLeft,
  Scale,
  FileCheck,
  AlertCircle,
  CheckCircle,
  XCircle,
  Gavel,
} from 'lucide-react';

export default function TermsOfServicePage() {
  return (
    <>
      {/* Hero Section */}
      <section className="relative min-h-[400px] flex items-center overflow-hidden bg-gradient-to-br from-gray-50 to-white">
        <BackgroundPattern variant="grid" opacity={0.08} className="text-gray-400" />

        <Container className="relative z-10">
          <div className="max-w-4xl">
            <Link
              href="/"
              className="inline-flex items-center text-[#116366] hover:text-[#0d4d50] mb-6 font-medium"
            >
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back to Home
            </Link>

            <div className="flex items-center gap-4 mb-4">
              <div className="w-16 h-16 rounded-xl bg-gradient-to-br from-[#116366] to-[#14b8a6] flex items-center justify-center">
                <Scale className="w-8 h-8 text-white" />
              </div>
              <div>
                <h1 className="text-4xl md:text-5xl font-bold text-gray-900">
                  Terms of Service
                </h1>
                <p className="text-gray-600 mt-2">Last updated: January 17, 2025</p>
              </div>
            </div>

            <p className="text-lg text-gray-600">
              Please read these terms and conditions carefully before using our services.
            </p>
          </div>
        </Container>
      </section>

      {/* Content Section */}
      <Section className="bg-white">
        <Container>
          <div className="max-w-4xl mx-auto">
            <div className="prose prose-gray max-w-none">

              {/* Agreement */}
              <div className="mb-12">
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-10 h-10 rounded-lg bg-[#116366]/10 flex items-center justify-center">
                    <FileCheck className="w-5 h-5 text-[#116366]" />
                  </div>
                  <h2 className="text-2xl font-bold text-gray-900 m-0">Agreement to Terms</h2>
                </div>
                <p className="text-gray-600 leading-relaxed">
                  These Terms of Service ("Terms") constitute a legally binding agreement between you and
                  CV Autobot Wijaya Solution ("Company", "we", "us", or "our") concerning your access to and use
                  of our website and services.
                </p>
                <p className="text-gray-600 leading-relaxed">
                  By accessing or using our services, you agree to be bound by these Terms. If you do not agree
                  with these Terms, you must not access or use our services.
                </p>
              </div>

              {/* Services Provided */}
              <div className="mb-12">
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-10 h-10 rounded-lg bg-[#116366]/10 flex items-center justify-center">
                    <CheckCircle className="w-5 h-5 text-[#116366]" />
                  </div>
                  <h2 className="text-2xl font-bold text-gray-900 m-0">Services Provided</h2>
                </div>
                <p className="text-gray-600 leading-relaxed">
                  Autobot provides the following services:
                </p>
                <ul className="space-y-2 text-gray-600">
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#14b8a6] mt-2 mr-3 flex-shrink-0"></span>
                    <span>Custom software development and IT consulting</span>
                  </li>
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#14b8a6] mt-2 mr-3 flex-shrink-0"></span>
                    <span>AI/LLM implementation and integration services</span>
                  </li>
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#14b8a6] mt-2 mr-3 flex-shrink-0"></span>
                    <span>Industry-specific software solutions (Healthcare, Education, Retail, Corporate)</span>
                  </li>
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#14b8a6] mt-2 mr-3 flex-shrink-0"></span>
                    <span>IT manpower and talent placement services</span>
                  </li>
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#14b8a6] mt-2 mr-3 flex-shrink-0"></span>
                    <span>Cloud solutions and cybersecurity services</span>
                  </li>
                </ul>
              </div>

              {/* User Obligations */}
              <div className="mb-12">
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-10 h-10 rounded-lg bg-[#116366]/10 flex items-center justify-center">
                    <AlertCircle className="w-5 h-5 text-[#116366]" />
                  </div>
                  <h2 className="text-2xl font-bold text-gray-900 m-0">User Obligations</h2>
                </div>
                <p className="text-gray-600 leading-relaxed">
                  By using our services, you agree to:
                </p>
                <ul className="space-y-2 text-gray-600">
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#14b8a6] mt-2 mr-3 flex-shrink-0"></span>
                    <span>Provide accurate, current, and complete information</span>
                  </li>
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#14b8a6] mt-2 mr-3 flex-shrink-0"></span>
                    <span>Maintain the confidentiality of your account credentials</span>
                  </li>
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#14b8a6] mt-2 mr-3 flex-shrink-0"></span>
                    <span>Use our services only for lawful purposes</span>
                  </li>
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#14b8a6] mt-2 mr-3 flex-shrink-0"></span>
                    <span>Not attempt to gain unauthorized access to our systems</span>
                  </li>
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#14b8a6] mt-2 mr-3 flex-shrink-0"></span>
                    <span>Respect all intellectual property rights</span>
                  </li>
                </ul>
              </div>

              {/* Prohibited Activities */}
              <div className="mb-12">
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-10 h-10 rounded-lg bg-[#116366]/10 flex items-center justify-center">
                    <XCircle className="w-5 h-5 text-[#116366]" />
                  </div>
                  <h2 className="text-2xl font-bold text-gray-900 m-0">Prohibited Activities</h2>
                </div>
                <p className="text-gray-600 leading-relaxed">
                  You may not use our services to:
                </p>
                <ul className="space-y-2 text-gray-600">
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-red-500 mt-2 mr-3 flex-shrink-0"></span>
                    <span>Violate any applicable laws or regulations</span>
                  </li>
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-red-500 mt-2 mr-3 flex-shrink-0"></span>
                    <span>Infringe on intellectual property rights of others</span>
                  </li>
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-red-500 mt-2 mr-3 flex-shrink-0"></span>
                    <span>Transmit harmful code, viruses, or malware</span>
                  </li>
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-red-500 mt-2 mr-3 flex-shrink-0"></span>
                    <span>Harass, abuse, or harm other users</span>
                  </li>
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-red-500 mt-2 mr-3 flex-shrink-0"></span>
                    <span>Engage in fraudulent or deceptive practices</span>
                  </li>
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-red-500 mt-2 mr-3 flex-shrink-0"></span>
                    <span>Reverse engineer or attempt to extract source code</span>
                  </li>
                </ul>
              </div>

              {/* Intellectual Property */}
              <div className="mb-12">
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-10 h-10 rounded-lg bg-[#116366]/10 flex items-center justify-center">
                    <Gavel className="w-5 h-5 text-[#116366]" />
                  </div>
                  <h2 className="text-2xl font-bold text-gray-900 m-0">Intellectual Property Rights</h2>
                </div>

                <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">Our Property</h3>
                <p className="text-gray-600 leading-relaxed">
                  All content, features, and functionality on our website and in our services, including but not limited to:
                </p>
                <ul className="space-y-2 text-gray-600">
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#14b8a6] mt-2 mr-3 flex-shrink-0"></span>
                    <span>Text, graphics, logos, icons, images, audio clips, video clips</span>
                  </li>
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#14b8a6] mt-2 mr-3 flex-shrink-0"></span>
                    <span>Software code, algorithms, and technical documentation</span>
                  </li>
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#14b8a6] mt-2 mr-3 flex-shrink-0"></span>
                    <span>Trademarks, service marks, and trade names</span>
                  </li>
                </ul>
                <p className="text-gray-600 leading-relaxed mt-4">
                  are owned by or licensed to CV Autobot Wijaya Solution and are protected by Indonesian and international
                  copyright, trademark, and other intellectual property laws.
                </p>

                <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">Custom Development Projects</h3>
                <p className="text-gray-600 leading-relaxed">
                  For custom software development projects, intellectual property rights will be defined in separate
                  project agreements. Typically:
                </p>
                <ul className="space-y-2 text-gray-600">
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#14b8a6] mt-2 mr-3 flex-shrink-0"></span>
                    <span>Client owns the final custom-built application</span>
                  </li>
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#14b8a6] mt-2 mr-3 flex-shrink-0"></span>
                    <span>Autobot retains rights to reusable components and frameworks</span>
                  </li>
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#14b8a6] mt-2 mr-3 flex-shrink-0"></span>
                    <span>Third-party components remain subject to their respective licenses</span>
                  </li>
                </ul>
              </div>

              {/* Payment Terms */}
              <div className="mb-12">
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-10 h-10 rounded-lg bg-[#116366]/10 flex items-center justify-center">
                    <FileCheck className="w-5 h-5 text-[#116366]" />
                  </div>
                  <h2 className="text-2xl font-bold text-gray-900 m-0">Payment Terms</h2>
                </div>
                <ul className="space-y-2 text-gray-600">
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#14b8a6] mt-2 mr-3 flex-shrink-0"></span>
                    <span>Payment terms will be specified in individual project agreements or invoices</span>
                  </li>
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#14b8a6] mt-2 mr-3 flex-shrink-0"></span>
                    <span>All prices are in Indonesian Rupiah (IDR) unless otherwise stated</span>
                  </li>
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#14b8a6] mt-2 mr-3 flex-shrink-0"></span>
                    <span>Late payments may incur additional fees as specified in agreements</span>
                  </li>
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#14b8a6] mt-2 mr-3 flex-shrink-0"></span>
                    <span>We reserve the right to suspend services for non-payment</span>
                  </li>
                </ul>
              </div>

              {/* Warranties and Disclaimers */}
              <div className="mb-12">
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-10 h-10 rounded-lg bg-[#116366]/10 flex items-center justify-center">
                    <AlertCircle className="w-5 h-5 text-[#116366]" />
                  </div>
                  <h2 className="text-2xl font-bold text-gray-900 m-0">Warranties and Disclaimers</h2>
                </div>
                <p className="text-gray-600 leading-relaxed">
                  We strive to provide high-quality services, but:
                </p>
                <ul className="space-y-2 text-gray-600">
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#14b8a6] mt-2 mr-3 flex-shrink-0"></span>
                    <span>Services are provided "as is" and "as available"</span>
                  </li>
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#14b8a6] mt-2 mr-3 flex-shrink-0"></span>
                    <span>We do not guarantee uninterrupted or error-free service</span>
                  </li>
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#14b8a6] mt-2 mr-3 flex-shrink-0"></span>
                    <span>Specific warranties for deliverables will be outlined in project agreements</span>
                  </li>
                </ul>
              </div>

              {/* Limitation of Liability */}
              <div className="mb-12">
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-10 h-10 rounded-lg bg-[#116366]/10 flex items-center justify-center">
                    <Scale className="w-5 h-5 text-[#116366]" />
                  </div>
                  <h2 className="text-2xl font-bold text-gray-900 m-0">Limitation of Liability</h2>
                </div>
                <p className="text-gray-600 leading-relaxed">
                  To the maximum extent permitted by Indonesian law:
                </p>
                <ul className="space-y-2 text-gray-600">
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#14b8a6] mt-2 mr-3 flex-shrink-0"></span>
                    <span>We shall not be liable for indirect, incidental, or consequential damages</span>
                  </li>
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#14b8a6] mt-2 mr-3 flex-shrink-0"></span>
                    <span>Our total liability shall not exceed the amount paid for the specific service</span>
                  </li>
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#14b8a6] mt-2 mr-3 flex-shrink-0"></span>
                    <span>Liability limitations do not apply to cases of gross negligence or willful misconduct</span>
                  </li>
                </ul>
              </div>

              {/* Termination */}
              <div className="mb-12">
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-10 h-10 rounded-lg bg-[#116366]/10 flex items-center justify-center">
                    <XCircle className="w-5 h-5 text-[#116366]" />
                  </div>
                  <h2 className="text-2xl font-bold text-gray-900 m-0">Termination</h2>
                </div>
                <p className="text-gray-600 leading-relaxed">
                  We may terminate or suspend your access to our services immediately, without prior notice,
                  for any reason, including but not limited to:
                </p>
                <ul className="space-y-2 text-gray-600">
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#14b8a6] mt-2 mr-3 flex-shrink-0"></span>
                    <span>Breach of these Terms</span>
                  </li>
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#14b8a6] mt-2 mr-3 flex-shrink-0"></span>
                    <span>Non-payment for services</span>
                  </li>
                  <li className="flex items-start">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#14b8a6] mt-2 mr-3 flex-shrink-0"></span>
                    <span>Fraudulent or illegal activity</span>
                  </li>
                </ul>
              </div>

              {/* Governing Law */}
              <div className="mb-8">
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-10 h-10 rounded-lg bg-[#116366]/10 flex items-center justify-center">
                    <Gavel className="w-5 h-5 text-[#116366]" />
                  </div>
                  <h2 className="text-2xl font-bold text-gray-900 m-0">Governing Law</h2>
                </div>
                <p className="text-gray-600 leading-relaxed">
                  These Terms shall be governed by and construed in accordance with the laws of the Republic of Indonesia,
                  without regard to its conflict of law provisions. Any disputes arising from these Terms shall be
                  subject to the exclusive jurisdiction of the courts in Jakarta, Indonesia.
                </p>
              </div>

              {/* Contact */}
              <div className="bg-gradient-to-br from-[#116366]/5 to-[#14b8a6]/5 border border-[#116366]/20 rounded-lg p-6">
                <h3 className="text-lg font-semibold text-gray-900 mb-3">Questions About These Terms?</h3>
                <p className="text-gray-600 leading-relaxed text-sm mb-4">
                  If you have any questions about these Terms of Service, please contact us:
                </p>
                <div className="space-y-1 text-sm">
                  <p className="text-gray-900 font-semibold">CV Autobot Wijaya Solution</p>
                  <p className="text-gray-600">Email: legal@autobot.co.id</p>
                  <p className="text-gray-600">Phone: +62 812 3456 7890</p>
                  <p className="text-gray-600">NIB: 1307240020719</p>
                </div>
              </div>

            </div>
          </div>
        </Container>
      </Section>
    </>
  );
}

// apps/wasigap/pages/terms-of-service.vue
<script setup lang="ts">
useSeoMeta({
  title: 'Terms of Service — WaSigap',
  description: 'WaSigap Terms of Service. Rules and responsibilities for using the WaSigap AI WhatsApp automation and CRM platform by AutobotWS.',
  ogTitle: 'Terms of Service — WaSigap',
  ogDescription: 'Terms of Service for WaSigap AI WhatsApp Automation Platform by AutobotWS.',
  ogUrl: 'https://wa.autobot.co.id/terms-of-service',
  ogImage: 'https://wa.autobot.co.id/logo.png',
})

useHead({
  link: [{ rel: 'canonical', href: 'https://wa.autobot.co.id/terms-of-service' }],
})
</script>

<template>
  <div class="bg-slate-50">
    <section class="border-b border-slate-200 bg-white py-12">
      <div class="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
        <p class="text-sm font-extrabold uppercase tracking-widest text-slate-500">Legal</p>
        <h1 class="mt-3 text-5xl font-black tracking-tight text-slate-950">Terms of Service</h1>
        <p class="mt-4 text-sm text-slate-500">Last updated: June 2026 · Applies to wa.autobot.co.id and WaSigap services</p>
      </div>
    </section>

    <section class="py-16">
      <div class="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
        <div class="grid gap-8">

          <div class="rounded-[24px] border border-slate-200 bg-white p-7 lg:p-8">
            <h2 class="text-2xl font-extrabold text-slate-950">1. Acceptance of Terms</h2>
            <p class="mt-4 text-base leading-8 text-slate-600">
              By accessing or using WaSigap services at <strong>https://wa.autobot.co.id</strong>, you agree to be bound by these Terms of Service. WaSigap is operated by AutobotWS under CV Autobot Wijaya Solution ("we", "us", or "our"). If you do not agree to these terms, do not use the service.
            </p>
          </div>

          <div class="rounded-[24px] border border-slate-200 bg-white p-7 lg:p-8">
            <h2 class="text-2xl font-extrabold text-slate-950">2. Service Description</h2>
            <p class="mt-4 text-base leading-8 text-slate-600">
              WaSigap is provided as a WhatsApp automation, CRM, and AI assistant platform for legitimate business communication. The service enables businesses to:
            </p>
            <ul class="mt-5 grid gap-2 text-sm leading-7 text-slate-600">
              <li>Automate WhatsApp customer replies using AI models.</li>
              <li>Manage customer contacts, conversation history, and CRM data.</li>
              <li>Schedule and send WhatsApp broadcast messages to customer lists.</li>
              <li>Create AI worker workflows for structured data collection through WhatsApp conversations.</li>
              <li>Generate AI-powered follow-up recommendations and automation workflows.</li>
            </ul>
          </div>

          <div class="rounded-[24px] border border-rose-50 bg-rose-50/60 p-7 lg:p-8">
            <h2 class="text-2xl font-extrabold text-slate-950">3. Prohibited Uses</h2>
            <p class="mt-4 text-base leading-8 text-slate-600">
              Users must not use WaSigap for any of the following prohibited activities:
            </p>
            <ul class="mt-5 grid gap-3 text-sm leading-7 text-slate-700">
              <li class="flex items-start gap-3">
                <span class="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-rose-500" />
                <span><strong>Spam and mass unsolicited messaging:</strong> Sending bulk, unsolicited, or deceptive messages to contacts who have not consented to receive communications.</span>
              </li>
              <li class="flex items-start gap-3">
                <span class="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-rose-500" />
                <span><strong>Fraud and deception:</strong> Using WaSigap to impersonate others, conduct phishing attacks, or deceive customers or third parties.</span>
              </li>
              <li class="flex items-start gap-3">
                <span class="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-rose-500" />
                <span><strong>Illegal activities:</strong> Any use of the platform for activities that violate Indonesian law or applicable international regulations.</span>
              </li>
              <li class="flex items-start gap-3">
                <span class="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-rose-500" />
                <span><strong>Harassment:</strong> Sending harassing, threatening, abusive, or discriminatory messages to any person or group.</span>
              </li>
              <li class="flex items-start gap-3">
                <span class="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-rose-500" />
                <span><strong>Misleading content:</strong> Distributing false information, fake promotions, misleading claims, or deceptive marketing content.</span>
              </li>
              <li class="flex items-start gap-3">
                <span class="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-rose-500" />
                <span><strong>Unauthorized scraping:</strong> Using WaSigap to scrape, harvest, or collect contact data from WhatsApp or other platforms without proper authorization.</span>
              </li>
              <li class="flex items-start gap-3">
                <span class="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-rose-500" />
                <span><strong>Abusive automation:</strong> Creating automated workflows that abuse the WhatsApp platform, violate WhatsApp's terms of service, or risk the service accounts of other WaSigap users.</span>
              </li>
            </ul>
          </div>

          <div class="rounded-[24px] border border-slate-200 bg-white p-7 lg:p-8">
            <h2 class="text-2xl font-extrabold text-slate-950">4. User Responsibilities</h2>
            <p class="mt-4 text-base leading-8 text-slate-600">Users are responsible for:</p>
            <ul class="mt-5 grid gap-3 text-sm leading-7 text-slate-600">
              <li class="flex items-start gap-3">
                <span class="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-emerald-500" />
                <span>Complying with WhatsApp's policies, terms of service, and messaging guidelines at all times.</span>
              </li>
              <li class="flex items-start gap-3">
                <span class="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-emerald-500" />
                <span>Complying with applicable local laws and regulations, including data protection requirements and consumer protection laws in Indonesia.</span>
              </li>
              <li class="flex items-start gap-3">
                <span class="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-emerald-500" />
                <span>Obtaining proper consent from customers and contacts before sending automated messages or broadcasts.</span>
              </li>
              <li class="flex items-start gap-3">
                <span class="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-emerald-500" />
                <span>Maintaining the security and confidentiality of their WaSigap account credentials.</span>
              </li>
              <li class="flex items-start gap-3">
                <span class="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-emerald-500" />
                <span>Ensuring that AI-generated replies sent to customers are appropriate, accurate, and compliant with their industry's regulations.</span>
              </li>
            </ul>
          </div>

          <div class="rounded-[24px] border border-slate-200 bg-white p-7 lg:p-8">
            <h2 class="text-2xl font-extrabold text-slate-950">5. Account Suspension and Termination</h2>
            <p class="mt-4 text-base leading-8 text-slate-600">
              WaSigap may limit, suspend, or terminate accounts that:
            </p>
            <ul class="mt-5 grid gap-2 text-sm leading-7 text-slate-600">
              <li>Violate these Terms of Service or WaSigap's usage policies.</li>
              <li>Abuse the platform or infrastructure, including excessive automated requests that affect service quality for other users.</li>
              <li>Create risk for the platform, other users, or third parties.</li>
              <li>Are involved in fraud, illegal activities, or harmful conduct.</li>
            </ul>
            <p class="mt-4 text-sm leading-7 text-slate-600">
              We will attempt to provide notice before suspension where possible. In cases of severe violation or active harm to the platform, immediate suspension may occur without prior notice.
            </p>
          </div>

          <div class="rounded-[24px] border border-slate-200 bg-white p-7 lg:p-8">
            <h2 class="text-2xl font-extrabold text-slate-950">6. Payment Terms</h2>
            <p class="mt-4 text-base leading-8 text-slate-600">
              WaSigap Lifetime Access is offered as a one-time payment. All payments are final unless otherwise agreed in writing. Additional AI credit packages, add-ons, or enterprise plans may have separate payment terms communicated at the time of purchase.
            </p>
          </div>

          <div class="rounded-[24px] border border-slate-200 bg-white p-7 lg:p-8">
            <h2 class="text-2xl font-extrabold text-slate-950">7. Limitation of Liability</h2>
            <p class="mt-4 text-base leading-8 text-slate-600">
              WaSigap is provided "as is" without warranties of any kind. We do not guarantee uninterrupted service, and we are not liable for indirect, incidental, or consequential damages arising from the use of the platform. Our total liability is limited to the amount paid by the user for WaSigap services.
            </p>
          </div>

          <div class="rounded-[24px] border border-slate-200 bg-white p-7 lg:p-8">
            <h2 class="text-2xl font-extrabold text-slate-950">8. Changes to Terms</h2>
            <p class="mt-4 text-base leading-8 text-slate-600">
              We may update these Terms of Service from time to time. Changes will be posted at <strong>https://wa.autobot.co.id/terms-of-service</strong> with an updated date. Continued use of WaSigap after changes constitutes acceptance of the updated terms.
            </p>
          </div>

          <div class="rounded-[24px] border border-slate-200 bg-white p-7 lg:p-8">
            <h2 class="text-2xl font-extrabold text-slate-950">9. Contact</h2>
            <p class="mt-4 text-base leading-8 text-slate-600">
              For questions about these Terms of Service, contact us at:
            </p>
            <div class="mt-4 grid gap-2 text-sm">
              <p><strong class="text-slate-950">Email:</strong> <a href="mailto:support@autobot.co.id" class="text-emerald-700 hover:text-emerald-800">support@autobot.co.id</a></p>
              <p><strong class="text-slate-950">Company:</strong> CV Autobot Wijaya Solution</p>
              <p><strong class="text-slate-950">Website:</strong> <a href="https://wa.autobot.co.id" class="text-emerald-700 hover:text-emerald-800">https://wa.autobot.co.id</a></p>
            </div>
          </div>

        </div>

        <div class="mt-10 flex flex-wrap gap-4">
          <NuxtLink to="/privacy-policy" class="inline-flex items-center gap-2 rounded-xl border border-slate-300 bg-white px-5 py-3 text-sm font-bold text-slate-800 transition hover:bg-slate-50">
            Privacy Policy
          </NuxtLink>
          <NuxtLink to="/contact" class="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-5 py-3 text-sm font-bold text-white transition hover:bg-emerald-700">
            Contact Us
          </NuxtLink>
        </div>
      </div>
    </section>
  </div>
</template>
